### ISSUE TITLE
Changing Files And Helping Update The Website

### ISSUE THREAD

**Issue by alexandre433** [ShinDarth/TC-Home-page#3]
Hello,

After I edit the website files on my computer, how do I send it here?
I'm new to this.

Thank You In Advance!

**Comment by FrancescoBorzi** [comment]
hello and welcome, I use a tool named [FileZilla](https://filezilla-project.org/) to do that.

Remember that Google is your friend, you will find a lot of explanations to achieve such a common task ;)
